import { CustomImage } from "@/sanity/types";
import { urlFor } from "@/sanity/image";
import Image from "next/image";

// Define the Props using your autogenerated type
type SanityImagePropType = {
    image: CustomImage | null | undefined; // Handle potential nulls from GROQ
    className?: string;
    sizes?: string;
    width?: number;
}

export default function SanityImage({
    image,
    className,
    sizes = "100vw",
    width = 1200,
}: SanityImagePropType) {
    if (!image) return null;

    // Use optional chaining to safely extract values from your 'file' property
    const asset = image.file?.asset;
    const hotspot = image.file?.hotspot;
    const crop = image.file?.crop;

    // If the asset reference doesn't exist, we can't build a URL
    if (!asset?._ref) return null;

    const src = urlFor({
        _type: "image",
        asset,
        hotspot,
        crop
    })
        .width(width)
        .quality(80)
        .auto("format")
        .url();

    const hotspotStyle: React.CSSProperties = hotspot?.x && hotspot?.y
        ? { objectPosition: `${hotspot.x * 100}% ${hotspot.y * 100}%` }
        : { objectPosition: "center" };

    return (
        <Image
            src={src}
            alt={image.alt || ""}
            fill
            sizes={sizes}
            style={hotspotStyle}
            className={`object-cover ${className ?? ""}`}
        />
    );
}